Android: Fix Builderror due to unused tileCount variable
The Android build on CI failed with the following error
message:

../../qgroundcontrol/qgroundcontrol/src/QtLocationPlugin/QGCTileCacheWorker.cpp:510:21: error: variable 'tileCount' set but not used [-Werror,-Wunused-but-set-variable]
221
            quint64 tileCount = 0;

The tileCount variable is not used. I removed the variable.